# Generated by Django 5.0.8 on 2024-08-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
