# Generated by Django 5.0.8 on 2024-08-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_info', '0002_publications_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
