# Generated by Django 5.0.8 on 2024-08-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_info', '0005_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
